progval/Limnoria

plugins/Filter/plugin.py
=> Filter: fix 'outfilter stripcolor' (Closes #661)

scripts/supybot-wizard
=> Wizard: Add prompt for file to save to

requirements.txt, src/conf.py, src/irclib.py
=> irclib: add support for SASL ECDSA-NIST256P-CHALLENGE

src/irclib.py
https://github.com/ProgVal/Limnoria/issues/854#issuecomment-70414650
=> Fix registration timeout when SASL is refused

plugins/RSS/README.md
I hope this is easier to understand than the previous format that was a little confusing.
=> RSS: rewrite basic usage in README

plugins/ShrinkUrl/config.py, plugins/ShrinkUrl/locales/fi.po, plugins/ShrinkUrl/locales/fr.po, plugins/ShrinkUrl/locales/it.po, plugins/ShrinkUrl/messages.pot, plugins/ShrinkUrl/plugin.py, plugins/ShrinkUrl/test.py
> Please note: Adding new links has been disabled since September 2014 after 14 months notice.
Source: http://metamark.net/
=> ShrinkUrl: Remove xrl.us

plugins/Karma/config.py, plugins/Karma/plugin.py, plugins/Karma/test.py
This is essentially the better version of #1002, but making it a config option instead.
=> Karma: add an option to limit Karma to nicks 

plugins/Aka/plugin.py, plugins/Aka/test.py
=> Aka: add a 'search' command.

test/test_yn.py
=> tests: Use internal mock from Python 3.3+ if available

CONTRIBUTING.md
"enough" comes after the adjective.
=> CONTRIBUTING.md: Fix grammar

plugins/ShrinkUrl/config.py, plugins/ShrinkUrl/plugin.py
Login+ApiKey required for it to function.
=> ShrinkUrl plugin, add BitLy support.

src/irclib.py, test/test_irclib.py
~~I didn't test the tests yet (no pun intended).~~
**Update:** Tests passing for me now!
=> Fix capability negotiation

plugins/Google/plugin.py, plugins/Google/test.py
The old translate function restored with a new working URL.
=> Restore Google translate

plugins/Filter/plugin.py
=> Strip colour before applying new colour in Filter.rainbow and colorize

plugins/Channel/plugin.py
=> Channel: fix help text in "cycle" command

src/conf.py
=> conf: fix help for verifyCertificates

plugins/Google/plugin.py
=> Google: add DDG plugin with py2/py3 support

plugins/Google/plugin.py
"import json" was being done twice. cgi, time, and socket all appear to be unused.
=> Google: remove unused & duplicated imports

plugins/Misc/plugin.py
=> change abuse command flood to except trusted users instead of just owners

.travis.yml
=> trevis: also test for 3.5 stable move to 3.6-dev

plugins/Factoids/plugin.py
=> Factoids: add missing Raise in requireVoice checks

plugins/Math/plugin.py
I broke this with my previous commit related to this.
=> Math: Fix round() with single argument in 'calc' command

scripts/supybot
This is probably better than leaving them as raw strings.
=> Substitute $nick and friends with <console> when exiting on Ctrl-C

plugins/Admin/plugin.py, plugins/Network/plugin.py
=> Network: add all+server+channels and all+channels commands

src/conf.py
=> Support `[ipv6]:port` format

plugins/QuoteGrabs/plugin.py
Reported on [https://bugs.debian.org/945569](https://bugs.debian.org/945569)
=> fix SyntaxWarning

README.md
Added python3-wheel dependency, otherwise I got an error running bdist_wheel
=> Update TL;DR install instructions with missing dependency

plugins/Misc/plugin.py, src/conf.py
The channel and network arguments were incorrectly swapped
=> Fix getSpecific usage

locales/de.po
Added a few missing translations in Deutsch.
They are not perfect. Better than having nothing I guess  ¯\_(ツ)_/¯ 
I may add a few more in future if I find some free time.
=> Missing German translations

src/utils/math_evaluator.py
=> Add modulo operator to new math evaluator

plugins/Google/parser.py
This commit gets the Google plugin working again.
=> Google: Fix plugin.

plugins/Herald/plugin.py
Fixes https://github.com/ProgVal/Limnoria/issues/1372
=> Herald: Throttle default heralds.

src/conf.py
Closes https://github.com/ProgVal/Limnoria/issues/1382
=> Selectable User-Agent for HTTP requests

src/conf.py
Fixes typo in https://github.com/ProgVal/Limnoria/pull/1423
=> Fix typo. HttpUserAgent -> HttpUserAgents

plugins/Google/plugin.py
Fixes https://github.com/ProgVal/Limnoria/issues/1382#issuecomment-654617022. This also provides case consistency (User-Agent vs. User-agent) across all plugins... See https://github.com/ProgVal/Limnoria/blob/138957676ec8c974dde1e45be81a37691f17434c/src/utils/web.py#L120 for further confirmation...
=> Google: Set User-Agent override.

plugins/Scheduler/plugin.py, plugins/Scheduler/test.py
=> add unrestricted text reminder scheduling commands as scheduler.add can be subject to abuse 

plugins/Services/plugin.py, plugins/Services/test.py
Please review, partially discussed on IRC.  Since there's a bunch of fixes, I recommend going commit by commit.
=> Per network services

.github/workflows/test.yml, plugins/Math/plugin.py, plugins/Math/test.py
=> Math: make @icalc fail early when result is too large

plugins/String/plugin.py, plugins/String/test.py
This allows them to support emoji ZWJ sequences, which render like one character but are actually multiple.
=> String: allow multi-character inputs in "ord" and "unicodename"

plugins/Owner/plugin.py, plugins/Owner/test.py
For example:
```
20:29:18 <val> valtest: ircquote @label=abcd WHOIS val
20:29:24 <valtest> val: @label=abcd :testnet.ergo.chat BATCH +4 labeled-response
20:29:26 <valtest> val: @time=2023-06-04T20:29:18.331Z;batch=4 :testnet.ergo.chat 311 valtest val ~u 8dcdfccjgu8zk.oragono * :Val Lorentz
20:29:28 <valtest> val: @time=2023-06-04T20:29:18.331Z;batch=4 :testnet.ergo.chat 319 valtest val :#limnoria-bots
20:29:30 <valtest> val: @time=2023-06-04T20:29:18.331Z;batch=4 :testnet.ergo.chat 671 valtest val :is using a secure connection
20:29:32 <valtest> val: @time=2023-06-04T20:29:18.331Z;batch=4 :testnet.ergo.chat 317 valtest val 0 1685531969 :seconds idle, signon time
20:29:34 <valtest> val: @time=2023-06-04T20:29:18.331Z;batch=4 :testnet.ergo.chat 318 valtest val :End of /WHOIS list
20:29:36 …
```
=> ircquote: Use labeled-response when possible to reply to the user

.github/workflows/test.yml, src/drivers/__init__.py, src/irclib.py, src/ircutils.py, test/test_irclib.py
thx to @SadieCat for reporting the issue
=> Fix STS parsing and handling of unchecked-TLS connections

test/test_irclib.py
=> Clean up SaslTestCase

plugins/PluginDownloader/plugin.py
I only have one plugin in my repo, but it would ease my task of installing it in a new environment if I could use PluginDownloader.
=> added a new repo for plugindownloader

plugins/Seen/plugin.py, plugins/Seen/test.py
Adds functionality to report on if the user is currently in the channel.
=> Seen: show when the target is currently in the channel

plugins/Internet/plugin.py
The previous was giving timeouts
=> Changed whois provider domain to whois.iana.org

plugins/NickAuth/locales/ru.po
=> Added russian locale to NickAuth plugin

locales/ru.po
Translated with lokalise.com. So export settings were a little limited (didn't find how to break lines to fit in 80 columns).
Translation is full, but has some *fuzzy* moments, will improve it in a future.
=> Added russian locale to limnoria

src/registry.py
=> Fix NormalizedString serialization splitting within escape sequences.

locales/ru.po
Update based on updated `message.pot`.
*P.S. but it seems like nothing new? Possibly poedit just touched file with its formatting...*
=> Updated russian translation

plugins/PluginDownloader/plugin.py
My plugins repo. All of them are mine with an exception of DuckHunt in which I made an emoji enhancement.
=> added spithash repo

plugins/Owner/test.py, src/plugin.py
=> Ignore stale renames defined for nonexistent commands
