progval/Limnoria

plugins/Filter/plugin.py

b78319b caused the first character in text to be cut off if it is not set to be replaced (e.g. a letter
when `config plugins.format.spellit.replaceletters` is off).

Filter: fix a bug introduced by b78319b

---

plugins/BadWords/plugin.py

- Remove unused `math` import.
- Don't kick halfop+ users or those with `channel,op`. Closes ProgVal/Limnoria#275.
- Fix a strange bug that causes the bot to kick on **everything** if the last defined bad word is removed (likely because `self.words` is empty and starts matching everything).

BadWords: bug fix, don't kick ops, remove unused import

---

plugins/Time/plugin.py

In `tztime`:
- Import pytz on load, not every time the command is called.
- Respect `plugins.time.format`.
- Use `irc.error(e, Raise=True)` instead of `return` in error handling.
- Fix a typo in the command description.
In `time`:
- simplify the code used for getting the format configuration (the if statement doesn't appear necessary and the option can just be fetched using `msg.args[0]`).

Time: refactor code, make tztime respect plugins.Time.format

---

src/conf.py

I am not fully sure on this change, but T is the official separator
between date and time and `date -Is` uses it.

src/conf.py: update reply.time.format

---

plugins/PluginDownloader/plugin.py

Antibody/supybot-plugins does not seem to work anymore, and causes errors with 'repolist'.
edit: 1000th pr/issue! :O

PluginDownloader: remove broken repo/unused import

---

plugins/NickAuth/plugin.py

NickAuth: fix leak of information if 'nick list' is used on a user without a configured nick

---

plugins/Aka/plugin.py

This adds a `--keys` option to `aka list` that allows viewing just the list of Akas, without their respective commands.

Aka: add 'aka list --keys'

---

plugins/Anonymous/README.md

Anonymous tell uses normal privmsg which doesn't check that services are
U-lined and not random user pretending to be them.
The correct way to identify to NickServ after already being connected is
`ircquote nickserv identify username password`.

Anonymous: remove dangerous example from README

---

src/irclib.py
test/test_irclib.py

Requesting multiple capabilities in one message will result in a NAK for all of them if at least one is not supported by the server.

Fix commit 30a026a

---

plugins/Debug/README.md
plugins/Debug/messages.pot
plugins/Debug/plugin.py

* Rewrite README.md based on `plugin help Debug`.
* Update string that I am not sure what it was, but it's not accurate anymore.
* add messages.pot & locales/.
* `.gitignore` is there to avoid git removing the directory and it can be removed as translations are added. I don't feel like translating at the moment and this seems very difficult plugin to translate if this should even be translatable.

Update Debug to time of shipping as default plugin

---

src/irclib.py

Temporary fix for #1028, though this may cause ECDSA-NIST256P-CHALLENGE to fail entirely (blocking the bot from connecting is a more severe issue).

irclib.py: fix an encoding error with Python 3 and SASL ECDSA-NIST256P-CHALLENGE

---

plugins/Google/plugin.py

This makes it easier to debug issues like #955 in the future, whether it be session limit exceeded, an API change, etc.
Also, remove duplicated checking clause for the HTTP error code.

Google: show the API's real error message instead of a generic error

---

plugins/ShrinkUrl/plugin.py

This allows things like '`x0 overdrive.pw`' to work properly, instead of requiring the command to be typed as '`x0 http://overdrive.pw'`. Most people won't be using URL shorteners for things that aren't `http(s)://` links anyways, so I think it should be safe to assume `http://` here.

ShrinkUrl: use httpUrl instead of url in wrap()

---

plugins/Admin/plugin.py

When `irc.reply()` is called with `private=True`, the bot will force a message in PM (or notice if configured to do so). IMO this makes more sense than forcing `channels` to be called in PM, as they both the same effect of preventing information leaks.

Admin.channels: call irc.reply() with private=True instead of requiring privacy

---

INSTALL.md
README.md

* README: use ircs:// link with \#supybot-fr too.
* INSTALL: fix links to documentation (docs/ was removed earlier)
* remove mentioning of packages and Windows (discussed on IRC, there have been issues and the Windows section is outdated and would just duplicate the real documentation.)
* fix lines in moving to Python 3, they should look nicer in text editor now.

Update INSTALL & README

---

plugins/Channel/config.py
plugins/Channel/plugin.py

This adds a new config variable `plugins.Channel.nicksInPrivate`. The idea of this change is to prevent people from spamming a channel with mass-highlights using the `nicks` command, without disabling or limiting it entirely. This is hopefully a sane default to minimize bot abuse.
(`nicks --count` is not affected by this option, just `nicks` without arguments is.)

Channel: prevent mass-highlights with 'nicks' by defaulting the output to private

---

src/i18n.py

Closes #1046
I used Admin for sources of what languages are supported as it's usually
recommended to start translating from there (first plugins, then core).

src/i18n.py: mention supported languages

---

plugins/User/plugin.py

Still to be tested in a live bot, but the individual lines work as expected.
Essentially verified.key_id is always the long user ID of the key which makes the signature, while verified.pubkey_fingerprint is always the fingerprint of the master key.  If the last 16 characters of the fingerprint match the signing key ID then keyid should be as it was (keyid = verified.key_id), but if they don't match then we want keyid set to the long key ID of the master key (keyid = verified.pubkey_fingerprint[-16:]).  Once keyid is set appropriately, the existing code continues as normal with the correct values.
This addresses the second bug listed in Issue #1045 (which I lodged a few hours ago).

Gpg extension - fix subkey/master key conflict

---

src/i18n.py

It's probably not so important, but I don't like them being in any
strange random order. Of course having English first would make sense as
it's the default, but I still prefer alphabetical order.

src/i18n.py: have languages in alphabetical order

---

plugins/Seen/plugin.py

This fixes a bug introduced by 38ff1a1137.

Seen: prevent KeyError when calling commands on channels that the bot is not in

---

plugins/Network/plugin.py

The current message ("xyz isn't on any non-secret channels or is using a channel-list hiding umode.") is long and awkwardly worded. 
This also removes an extra period from showing up at the end of the output.

Network.whois: simplify message when user isn't on any public channels

---

plugins/Admin/config.py
plugins/Admin/plugin.py
plugins/Owner/config.py
plugins/Owner/plugin.py
scripts/supybot
src/callbacks.py
src/ircutils.py

Closes #391.
This also makes the default part message the Supybot version instead of the nick's caller. Quit messages are optional anyways for IRC, so just having someone's nick inside a part message isn't very intuitive or meaningful. When `config plugins.admin.partmsg` is blank, simply no part message will be used.
edit: This also merges the changes in #1043 and supports other substitutions too (`$nick`, etc.).

Admin/Owner: substitute $version in quit and part messages (also make part messages configurable)

---

plugins/Admin/config.py
plugins/Admin/plugin.py
plugins/Admin/test.py
plugins/Channel/config.py
plugins/Channel/plugin.py
plugins/Channel/test.py

This is essentially two changes in one pull request because the changes depend on each other. Closes #79. Closes #1062.
- Move `part` command from Admin to Channel and require `#channel,op` instead of admin.
- `Channel.cycle`: allow specifying part message that defaults to `plugins.Channel.partMsg`.

Move 'part' command from Admin to Channel and use part messages in Channel.cycle

---

plugins/Channel/config.py
plugins/Channel/plugin.py

This is done via the config variable `supybot.plugins.Channel.rejoinDelay`. Closes #1011.
The timing of the rejoins isn't super-exact because of `schedule.addEvent()` being used (the bot might join one second slower than what's set), but it should be fine for most purposes. When `rejoinDelay` is turned off, everything skips the scheduling and the rejoin is actually instant.

Channel: allow adding an auto-rejoin delay

---

src/conf.py

conf.py: Remove reference to non-existent "user configuration variable"

---

plugins/ShrinkUrl/config.py
plugins/ShrinkUrl/plugin.py
plugins/ShrinkUrl/test.py

`ln-s.net` has been dead for over half a year now (#618); both their website homepage
and any previous shortened links return an HTTP 503. Thus, it isn't very
useful to leave this broken command lingering around...

ShrinkUrl: Remove ln (Closes #618).

---

.gitattributes

Fixes an issue where tags/releases do not ship the core test suite, as used by the automated Travis testing.
Basically, every tag that has been made, when the tarballs are downloaded, they come without the test folder.
I thought that it would be useful to re-include this, as I'd like testing in my packages for versioned releases to mimic the test suite that Limnoria is running through travis.

Remove test from .gitattributes

---

plugins/Channel/plugin.py
plugins/Channel/test.py

Voice requires halfop or above to set, and since having (half)op gives greater access than voice, restricting this pretty useless.

Channel: allow devoicing self

---

src/callbacks.py

This can help with debugging to find what plugins are passing invalid things to `registryValue()`.

callbacks.py: log plugin name in registryValue='text' errors

---

scripts/supybot

This is a stylistic change, which prevents things such as 0.9400000000001 seconds from showing up.

scripts/supybot: round total CPU time to 2 decimal places

---

src/ircutils.py

This reapplies content from commits 2b324203e7701ac1dd83e9879de2543e348f1499, 2628dc03c4743578f2b8e7320b7b4f5e4e715167, ef9fbc4a07db1c18ea5d805f0b4770cc17b152d8,
41effcea13b4a5831dd80835f47829027b39f19f, and 5f23855d278ad4d5527c90cc4000b2c2eddef971.
It also fixes an error caused by `strEqual` called as `ircutils.strEqual`, and behavior causing the `#` in a channel name to be cut off.

formatWhois: fix errors and restore formatting changes lost in supybot merge

---

plugins/Aka/plugin.py
plugins/Aka/test.py

Closes #1110.
There was a mistake in the previous logic: `matching` is supposed to be empty if nothing matches, not necessarily `aka_list`.

Aka.search: be case insensitive & handle "not found" errors correctly

---

plugins/Math/test.py
plugins/News/test.py
scripts/supybot-plugin-create
scripts/supybot-wizard

There are some places where `print()` is used to print a blank line. However, unless the future feature `print_function` is imported, that will print `()` in Python 2.

Add missing future imports for print_function

---

src/irclib.py

This fixes a regression introduced by #1122, when SASL is supported on a network but isn't configured/being used. This bug would've caused connections to fail and time out on these networks:
```
INFO 2015-06-12T17:42:59 espernet: Server acknowledged capabilities: account-notify extended-join multi-prefix sasl
ERROR 2015-06-12T17:42:59 Uncaught exception in Irc.feedMsg:
Traceback (most recent call last):
File "/home/gl/.local/lib/python3.4/site-packages/supybot/log.py", line 361, in m
return f(self, *args, **kwargs)
File "/home/gl/.local/lib/python3.4/site-packages/supybot/irclib.py", line 860, in feedMsg
method(msg)
File "/home/gl/.local/lib/python3.4/site-packages/supybot/irclib.py", line 1042, in doCap
self.doCapAck(msg)
File "/home/gl/.local/lib/python3.4/site-packages/supybot/irclib.py …
```

irclib: fix error when SASL is supported but not enabled for a network

---

src/conf.py

YouTube (as an example) has recently updated its site design again so the `<title>` element falls right out of the 4K mark, causing YouTube links to be ignored. This commit raises the default peeksize to 8K, which allows title snarfing to work again.
The difference between 4 and 8 kilobytes isn't that big, so I don't think this change would do any harm.

conf.py: raise protocols.http.peeksize to 8192

---

plugins/Praise/test.py
plugins/Quote/test.py
plugins/__init__.py
src/conf.py

This adds a new configuration variable, `supybot.databases.plugins.requireRegistration`, which defaults to `True` for maximum security. When this is disabled, unauthenticated users will be able to use commands such as `quote add` freely. This is really my rationale for this, as most IRC quote bots I know of don't require registration, and people didn't like how Supybot forced registration for adding quotes.
Internally, this allows storing a string (hostmask) where the user ID (integer) usually goes, and `checkChangeAllowed` will `return True` if the hostmask of the caller matches the hostmask stored.
I also fixed Praise's tests by making them channel specific. (Travis CI pointed this out during building)

Allow unregistered users to use 'add', 'remove', etc. in ChannelIdDatabasePlugin plugins

---

src/ircutils.py

Fixes #98: see https://github.com/ProgVal/Limnoria/issues/98#issuecomment-121519435. The case of hiding channels for umode `+i` *isn't standard across IRCds*, so I don't think implementing it would be correct.

ircutils.formatWhois: ignore channels that have +p set

---

src/ircutils.py
test/test_ircutils.py

New functions:
ircutils.italic to add
ircutils.stripItalic to remove
And remove italics in ircutils.stripFormatting.

Add support for italic formatting

---

plugins/Alias/config.py
plugins/Alias/plugin.py
plugins/Alias/test.py

711572b and fd53d8c are bugfixes.
54e9b4b - new feature, Alias.list command to list alias names, optionally filtered by --locked or --unlocked.
963a17c - new config option to allow relaxing the rules on alias names
d9b21dc (optional) - change default value for the new config option to a more relaxed one
I'm not sure what, if anything, needs doing about internationalisation and messages.pot though...

Alias improvements

---

plugins/Aka/plugin.py
plugins/Aka/test.py

This adds two mutually incompatible options to Aka list: `--locked` and `--unlocked`, similar to what's done in 54e9b4be098388c8d86140d76c8d9ea1cec2a7da.

Aka: allow filtering 'list' by Aka lock status

---

plugins/User/config.py
plugins/User/plugin.py

Controlled by new config value plugins.User.listInPrivate.
This avoids mass-highlights of people who use their IRC nick as their bot username.

Send User.list response in private

---

plugins/Filter/plugin.py
plugins/Filter/test.py

This makes `_squish()` a shared function to prevent code duplication. Also, remove duplicate a `testUnbinary` function, and add tests for this.

Filter: strip spaces in "unbinary" (Closes #1166)

---

plugins/BadWords/plugin.py

The check I added to fix this in #989 didn't quite work - this needs to check for `self.words()` (a set) instead of `self.words` (the config option object).

BadWords: truly fix the bot kicking people when badwords list is empty

---

plugins/Google/plugin.py

Fixes #1144
'ch' language code doesn't exist in Google Translate so naturally nothing comes back. Traditional chinese is 'zh-cn'. Using 'auto' also works.

Google: Handle empty results in translate.

---

plugins/Web/plugin.py
plugins/Web/test.py
src/utils/web.py

[Relevant Python issue.](http://bugs.python.org/issue23144)
With Python 3.5.0, Web returns an empty string as the title. The 'proper' solution to this is to force processing  by calling HTMLParser.close().
The fixed test case was failing on my machine because the actual title is capitalized.

Web & utils.web: Fix for HTMLParser in Python 3.5.0

---

src/irclib.py

The old code, which checked for "Closing Link" in the message, wouldn't have matched InspIRCd's way of closing connections (they send "Closing link" with a lowercase l):
```
DEBUG 2015-09-27T19:15:32 Incoming message (overdrive-irc): ERROR :Closing link: (LilyBot@0::1) [Quit: test]
```
If I remember correctly, this was causing some issues with autoreconnect not working on my network.

irclib: handle disconnections correctly for InspIRCd 2.0 networks

---

plugins/Web/plugin.py

This issue was bothering me for quite a while, as the title snarfer didn't cleanly strip newlines from titles. Not all sites are affected by this, but some, like the one below, are.
Sample link: http://googleblog.blogspot.com/2015/08/android-wear-now-works-with-iphones.html
Before: `<bot> 'Title: \nOfficial Google Blog: Android Wear now works with iPhones\n (at googleblog.blogspot.com)'`
After: `<bot> Title: Official Google Blog: Android Wear now works with iPhones (at googleblog.blogspot.com)`

Web: normalize whitespace in titles

---

src/drivers/Socket.py

I don't like the idea of using critical-level logging to nag people to switch to TLS. Encouraging encryption is a good cause, but it's not a *critical software error* and shouldn't be treated as such.

Socket: lower SSL related log level, and reword text to flow better

---

plugins/Network/plugin.py

c3dd5f8b64618de70414024c354b4867aaaa044c made plain text networks impossible to add. The getopts key needed to be changed from `ssl` to `nossl` in order to fix this.

Network: fix getopts key for --nossl

---

src/ircutils.py
test/test_ircutils.py
test/test_standardSubstitute.py

This is useful for setting the bot's quit message to things like "`Disconnect command received $nick@$network`", as the network field would then be automatically expanded.

ircutils: add $network to standard substitutions

---

src/conf.py
src/utils/net.py
src/utils/web.py

Use proxy handler/opener classes, instead of request.set_proxy, to avoid any potential [bugs](http://bugs.python.org/issue1424152#msg68861) in older Python versions.
If configured, use the HTTP proxy for HTTPS requests as well.
_(Tested fine on both Python 2.7.6 and 3.4.3)_
This commit is a prerequisite for future commits related to #1234.

Use HTTP proxy for HTTPS requests as well

---

plugins/ShrinkUrl/plugin.py

http://api.x0.no/ now redirects to https://x0.no/api/. The latter supports and serves HTTPS redirect links!

ShrinkUrl: Update API URL, now serving HTTPS links

---

plugins/Google/plugin.py

This might reduce confusion when people do things like "!google translate english to french hello", which produces no result.

Google: mention the format of language codes

---

plugins/Web/config.py
plugins/Web/plugin.py

This adds a snarferShowDomain option to optionally hide the domain ("(at site.abc)" text) in titleSnarfer output. Closes #1236.

Web: optionally hide the domain in titleSnarfer

---

plugins/Google/plugin.py

Google has since reformatted their docs and moved the language support info to a separate page.

Google: update link to supported languages list

---

plugins/Channel/plugin.py

In other words, use msg.prefix instead of network-dependent nickToHostmask() for capability checks. Closes #1233.

Channel: fix KeyError in combination with 'network command'

---

scripts/supybot

The reason this would be useful is related to #896 . 
I have been trying to get Limnoria running on OpenShift v3 partly by using https://github.com/ProgVal/docker-limnoria (which I have some modifications for) and using https://github.com/minishift/minishift to run a local OpenShift cluster. 
According to https://docs.python.org/2/library/shutil.html copy attempts to set the ,permission bits while copyfile just copies the contents. This change should therefore have no side-affects in day to day use but makes Limnoria usable on OpenShift.
In OpenShift the user ID is random (and you are not running as root) therefore I was getting 
```[Errno 1] Operation not permitted: '/var/supybot/supybot.conf.bak```

Use copyfile instead of copy

---

plugins/Owner/config.py
plugins/Owner/plugin.py

Someone asked how to remove the owner's username from announcements, so it may be useful to make this configurable instead of making them edit a core plugin's code which is not the best idea, or write another plugin.

Allow specifying the format of Owner.announce

---

src/ircutils.py

As strings, `'\x0f' == '\x0F'`, and `'\x1f' == '\x1F'`, meaning these extra replace calls are redundant.

ircutils: remove redundant str.replace calls

---

plugins/Math/plugin.py

The second argument of `round()` has to be an integer, and since every number is converted to a float to avoid using too much memory, a wrapper has to be added for this function. I've tested it with big numbers and it doesn't seem to cause any issue.

Math: Fix round() in calc command

---

plugins/Owner/plugin.py

It is fairly counterintuitive for plugins to read the IrcState history, only to find that the message it got is from the wrong network.
I'm not sure why the original Supybot chose to link all the history buffers together, as those lines came from before Supybot was introduced to Git.
Closes #1211.
----
I realize that this is a breaking API change, which may subtly break any plugins relying on history to be global. I don't know of any specific plugins that would break however...

Make irc.state.history network specific

---

plugins/PluginDownloader/plugin.py

This PR is two fold:
1) Add support for other branches to PluginDownloader (fixes #1293)
2) Add the Python 2 (legacy) branch of my repository as `GLolol-py2legacy`

Support non-master branches in PluginDownloader

---

plugins/Web/plugin.py

The web size command raises a TypeError exception (line 282 in plugin.py) on URLs that do not contain a "Content-Length" header, due to Python3 returning a key for it with the value 'None'.
In Python2: 
```
>>> fd.headers["Content-Type"]
'text/html; charset=UTF-8'
>>> fd.headers["Content-Length"]
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python2.7/rfc822.py", line 393, in __getitem__
return self.dict[name.lower()]
KeyError: 'content-length'
```
In Python3:
```
>>> fd.headers['Content-Type']
'text/html; charset=UTF-8'
>>> fd.headers['Content-Length']
>>> 
```
This PR works around that by checking if the Content-Type header returned is 'None', and if so manually raises an exception that gets caught later on.
This way, backwards compatibility is …

Fix exception raised due to lack of Content-Type on the Web plugin.

---

plugins/Config/plugin.py
plugins/Config/test.py
plugins/Debug/plugin.py
plugins/Debug/test.py
plugins/Karma/plugin.py
plugins/PluginDownloader/plugin.py
plugins/PluginDownloader/test.py
plugins/Unix/plugin.py
plugins/Unix/test.py
src/conf.py

This PR add a new configuration variable, named `supybot.commands.allowShell`, whose help:
> Allows this bot's owner user to use commands
> that grants them shell access. This commands exists in case you want to
> prevent MITM from the IRC network itself (vulnerable IRCd or IRCops)
> from gaining shell access to the bot's server by impersonating the owner.
> Setting this to False also disables plugins and commands that can be
> used to indirectly gain shell access.
When set to False, its effects are the following:
* Config plugin:
* Prevent changes to `supybot.commands.allowShell`, so it cannot be re-enabled by an attacker
* Prevent changes to variables in `supybot.directories.plugins`, so an attacker able to upload files on the server (eg. a web app / CMS) cannot load arbitrary code
* …

Add config variable supybot.commands.allowShell.

---

plugins/Config/plugin.py

-- deviated from normal '' line enclosure to allow use of ' in lines without escaping

Config: Don't use a prefix in _setValue (closes #1307)

---

plugins/NickAuth/plugin.py
src/irclib.py

in order to avoid external plugins to do again the same request with more arguments, as thiis request must be made per channel and can take a lot of time, it's rather better if core limnoria already shares all needed informations

Use of the most usefull arguments for WHOX

---

plugins/RSS/plugin.py

An AttributeError would be raised when a blacklist or a whitelist
would be set on feeds that miss either a title or a description.

RSS: Fix feeds with missing description or title

---

setup.py

The ceil() function was previously used in setup.py was removed by
commit c3a2c800f1c36adff0db9651c2d74c3f6a648f84. So we no longer need
it.

setup.py: Remove unneeded import of match for ceil() function

---

scripts/supybot-plugin-create
test/test_plugin_create.py

- cb33687: compactify import statements where applicable into `from supybot import abc, def, ...`
- af515ec: prefer `importlib` over `imp` on Python >= 3.4, where `imp` is deprecated

Fixes and tests to supybot-plugin-create; modernize the plugin template

---

plugins/Owner/plugin.py
src/callbacks.py
src/commands.py
src/irclib.py
src/ircmsgs.py
src/ircutils.py
test/test_callbacks.py
test/test_commands.py
test/test_irclib.py
test/test_ircutils.py
test/test_standardSubstitute.py

Not yet in plugins, I'll update plugins at the same time as for network-specific config vars, as the main use of `msg.channel` would be for calling `self.registryValue()`
Opinions on this?

Add `channel` attribute to IrcMsg, and start using it in the core

---

src/commands.py

In the unlikely event that a command `return`s an Exception (instead of `raise`ing it), it should not be raised up out of command.py.process()

only raise in command.py.process() when a raise was wrapped

---

plugins/RSS/plugin.py
plugins/RSS/test.py

I'm assuming `get_feed()` is the right call here. This seems to work fine with both name and URL added feeds on my bot.
Closes #1322.

RSS: add 'announce chans' command to list channels a feed is announced to

---

src/commands.py

This allows plugins to detect whether a search timed out or did not match, which are two distinct outcomes.
Currently this affects SedRegex: if the search on one message times out, it assumes that the regex did not match and moves on to the next message. Often times, this ends up causing the wrong message to be replaced.

regexp_wrapper: return None instead of False when search times out

---

plugins/Plugin/__init__.py
plugins/Plugin/plugin.py
plugins/Plugin/test.py
src/__init__.py

In particular, I rewrote the contributors command to be simpler and removed a bunch of legacy code. Namely:
- `contributors` no longer sorts people by contribution count; it wasn't obvious that this was a feature to begin with
- `contributors [nick]` no longer distinguishes between commands and non-commands. This wasn't documented all that clearly and was prone to false positives (e.g. "internationalization" would be considered a command when it isn't)
- Removed legacy handling in `contributors [nick]` of people marked as both author and contributor. In practice, nobody actually does this.

Refactor the Plugin command

---

plugins/Web/plugin.py

Hi. Sorry about ditching the original pull request #1371 After doing it wrongly against 'master' and being moved to 'testing' I think that starting from an original branch seems to be the right thing. Plus after reviewing your comments there I concluded that this pull request is a better approach.
Not sure why git ended by replacing entire contiguous blocks because the changes against master aren't so big if you compare.
Description:
- Adds general error catching (404,403,ssl mismatches etc) to logs and validates 'text' for further processing.
"  try:
(target, text) = utils.web.getUrlTargetAndContent(url, size=size,
timeout=timeout)
except Exception as e:
self.log.info('Web plugin TitleSnarfer: URL <%s> raised <%s>', url, str(e))
text = None
if text: "
- This is the best approach i could …

CatchTitleSnarferErrors

---

src/test.py

Closes #1392.
(On a side note, I tried adding this setting to `src/httpserver.py` by calling `configGroup.port.setValue(0)`, but that change didn't seem to stick.)

Aka: bind HTTP tests to a random port

---

plugins/Web/plugin.py
src/conf.py

Some websites autodetect the language based on the server location.
This PR adds a global variable that lets users override the served language by specifying the `Accept-Language` header.
The Web plugin has also been modified to implement channel-specific language settings.
```
<User> %web title https://twitter.com/
<Bot> Twitter. Ce qu'il se passe.
<User> %config supybot.protocols.http.requestLanguage "en-GB"
<Bot> Ok
<User> %web title https://twitter.com/
<Bot> Twitter. It's what's happening
```
Continuation of https://github.com/ProgVal/Limnoria/pull/1395

Add supybot.protocols.http.requestLanguage

---

src/utils/web.py

Fixes [bug](https://github.com/ProgVal/Limnoria/issues/1416) when handling URLs with a closing parenthesis ')'. e.g. https://en.wikipedia.org/wiki/Harley_Quinn_(TV_series)

Keep closing parenthesis when snarfing URLs

---

plugins/DDG/config.py
plugins/DDG/plugin.py
plugins/DDG/test.py

DDG redirect detection is currently broken, the first commit fixes that. DDG also uses the host IP to auto-detect region, the second commit adds a region config to allow setting the language/country of your choice. Also in the second commit is support for Safe Search, bringing DDG more in line with the Google plugin.

DDG: Fix redirects, add region/safeSearch configs.

---

src/conf.py

random.choice() should only be run after verifying the config has been set.

protocols.userAgents: prevent IndexError.

---

README.md

As Supybot upstream is unmaintained, having multiple channels adds to support overhead and makes conversations harder to follow. Also, #limnoria is already the larger of the two channels.
[skip ci]

README: point support channel to #limnoria

---

scripts/supybot-adduser
scripts/supybot-reset-password

running supybot-adduser (or supybot-reset-password) with a recent
python would result in the warning:
> ```
> /usr/local/bin/supybot-adduser:59: SyntaxWarning: "is not" with a literal. Did you mean "!="?
> if len(args) is not 1:
> ```
This commits corrects the syntax.
`

resolve warnings about 'is not' and integer comparisons

---

plugins/PluginDownloader/plugin.py

Many people are renaming their default branches from master to main or something else (I just renamed mine). Using HEAD works no matter what the default branch is named.

PluginDownloader: Change default branch from master to HEAD

---

plugins/Fediverse/test.py

At least in Debian CI they routinely timeout when they run in the
busiest server.
I haven't actually tested the new timeout, but since it's literally 5 times more (whilst still being half a second) I'm optimistic it ought to be enough!

increase the timeout for Fediverse's tests

---

src/conf.py
test/test_conf.py

If you have enough channels that the 512 byte message limit on the JOIN
message is hit then limnoria was losing the channel that put it over the
limit and not including it in the next JOIN message. This resulted in
losing one channel for every JOIN message that pushed us over 512 bytes.
We fix this by generating the JOIN message immediately after resetting
the channels list to ensure we include the channel that pushed us over
the limit. Then the next time through our JOIN msg construction we'll
add subsequent channels without forgetting the one that pushed us over.

Fix joins to many channels

---

src/callbacks.py
src/drivers/__init__.py
src/registry.py

There are small typos in:
- src/callbacks.py
- src/drivers/__init__.py
- src/registry.py
Fixes:
- Should read `plugins` rather than `pluings`.
- Should read `overridden` rather than `overrided`.
- Should read `explicitly` rather than `explicitely`.
Closes #1475

Bugfix typos [skip ci]

---

src/conf.py

Co-authored-by: MetaNova <MetaNova@users.noreply.github.com>

src/conf.py: fix typo in supybot.reply.error.withNotice

---

src/utils/web.py

Note: This uses a Python 3 specific syntax, which means that the minisix usage in utils.web probably isn't useful anymore.
A lot of APIs, including LastFM and GitHub, serve detailed API errors in the body text even if the request returned an error.
This allows plugins to track HTTP errors returned from urllib and present these detailed messages (although the syntax to do so isn't the prettiest).
An example with my LastFM plugin:
```diff
diff --git a/LastFM/plugin.py b/LastFM/plugin.py
index de9087d..9bf1366 100644
--- a/LastFM/plugin.py
+++ b/LastFM/plugin.py
@@ -42,6 +42,7 @@ import supybot.log as log
import supybot.ircdb as ircdb
import json
+import urllib.error
from datetime import datetime
from .local import accountsdb
@@ -80,15 +81,20 @@ class LastFM(callbacks.Plugin):
url = …
```

getUrlFd: chain the original exception so that plugins can handle them further

---

src/__init__.py
src/i18n.py
src/utils/__init__.py
src/utils/gen.py
src/utils/str.py

The previous implementation was messy and needlessly complicated
This simplifies the logic and removes hackiness by making utils/str.py
handle internationalization logic itself, instead of bending over
backwards to load logic from the parent package at import time.

utils: Rewrite i18n initialization

---

plugins/BadWords/config.py
plugins/BadWords/messages.pot
plugins/BadWords/plugin.py

Adds a `selfCensor` per channel setting to allow excepting a channel from the bot's censoring of its own messages.

Add ability to exclude channel from self censoring

---

plugins/PluginDownloader/plugin.py
plugins/PluginDownloader/test.py

The repos I've selected for removal are those that at a cursory glance, appears to only include plugins supporting Python 2 (`import config` / `import plugin` in `__init__.py`). Unsurprisingly, most of these also haven't been updated in ~10 years.
I'm also removing the automatic 2to3 step because the current heuristic is buggy, and automated porting alone is unlikely to fix plugins that are this old anyways (obsolete web APIs etc.). Attempting to load plugins with the outdated import style will still suggest 2to3 in the error message, so the hint is still there for people who want to try.
On a side note, `lib2to3` is apparently being deprecated in Python 3.11: https://docs.python.org/3/library/2to3.html#module-lib2to3

PluginDownloader cleanup: drop automatic 2to3 and legacy repos

---

plugins/MoobotFactoids/plugin.py

Attempt at #1490.
I have added usage examples which weren't documented, whilst attempting to follow the existing format and language.
I wasn't able to get a response from:
`<factoid key> ~= s/current value/new value/`
and hence I've left it undocumented.
Feel free to edit the language if desired.

for #1490 extend usage examples for moobotfactoids

---

plugins/Services/config.py
plugins/Services/plugin.py

Anope 2.x has renamed this to /ns recover
Closes GH-1510
Note: I haven't tested this because I don't really run my bot on that many networks anymore, and the original reporter didn't have time for it either. But it's a fairly simple change nonetheless...

Services: allow adjusting GHOST command

---

plugins/Network/plugin.py
plugins/Network/test.py
src/callbacks.py

Add a replyIrc parameter to ReplyIrcProxy to run a command on one network, but route the replies to another.
This fixes a long standing issue GH-556 where replies for remote commands are often lost to the void, as the nick of the caller may not exist on the target network (or worse, it could belong to a completely unrelated person).

Route commands from Network.command back to the original network

---

plugins/String/plugin.py

An re.error is raised when the function is called to check if trying to match the empty string.
Thus, move the try one level outside to cover that case as well.
Before:
```
<User> %re s/test/\1/ test
<Bot> An error has occurred and has been logged. Check the logs for more information.
```
After:
```
<User> %re s/test/\1/ test
<Bot> Error: invalid group reference 1 at position 1
```
Misc information
```
The current (running) version of this Limnoria is 2023.04.28, running on Python 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0].  The newest versions available online are 2023.01.28 (in master), 2023.04.28 (in testing).
```
```
ERROR 2023-05-12T15:07:01 supybot Uncaught exception in ['re'].
Traceback (most recent call last):
File …
```

String: Fix exception on invalid group reference

---

plugins/Network/plugin.py
src/irclib.py

Add command to manually initiate SASL

---

requirements.txt

The command was introduced in https://github.com/progval/Limnoria/pull/1310 and I imagine it missing from `requirements.txt` being an oversight.

requirements.txt: add ddate as an optional dependency for Time.ddate

---

.editorconfig
.gitattributes

As `.gitattributes` was already there I thought it might be a good idea to add end-of-line normalization of git from this decade.
- https://www.git-scm.com/docs/gitattributes#_end_of_line_conversion
-----
When writing #1560, I noticed that my `nvim` was making tabs which is against Limnoria's style guidelines. Thus I added `.editorconfig` that follows the [Limnoria style guidelines](https://limnoria.readthedocs.io/en/latest/develop/style.html) so [supported editors and plugins](https://editorconfig.org/#pre-installed) will automatically attempt to use four spaces as indentation and stay within 79 lines.
I am not sure if I should add it to `.gitattributes` as `export-ignore`, because someone could download the repository archive and send a patch by email or pastebin and thus benefit from …

Keep line-endings normalized & configure text editors to follow Limnoria style guidelines

---

plugins/Status/plugin.py

See https://github.com/progval/Limnoria/issues/1183
If accepted, could you please add the `hacktoberfest-accepted` label? I understand you do not want your repository to participate, but this PR still can.

report channel counts and modes in status

---

plugins/Misc/test.py
src/callbacks.py
test/test_callbacks.py

Seems to fix https://github.com/progval/Limnoria/issues/1455 
Again, if you decide to merge, please add the `hacktoberfest-accepted` label.

Ignore trailing whitespace when addressing the bot by nick at end

---

src/ircdb.py
test/test_ircdb.py

These do not pass the `ircutils.isUserHostmask` check despite being a valid `msg.prefix`. We should probably return gracefully here instead of forcing plugins to deal with such a case themselves.
Closes GH-1548

ircdb.checkIgnored: return False for messages from servers

---

src/scripts/limnoria_test.py

As discussed in #1061, here we use this:
https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory
to handle the creation of temporary directories. The files are not deleted in case there are any test failures, so they can be inspected.

Files are created in tmp dirs and they are cleaned if tests succeed (#1061)

---

plugins/Karma/plugin.py
plugins/Karma/test.py

The trailing characters `,` and `:` have been chosen as they are the most popular ones appended to tab completed nicks.
Solves #1495

Fix: Ignore trailing chars/spaces for Karma

---

src/utils/__init__.py
src/utils/file.py

First part of builtins mangling cleanup. As I mentioned in #1535 this function does not appear to be used in any repo currently active in PluginDownloader, so just removing this should be adequate.

Remove adding force to builtins (#1535)

---

src/callbacks.py
src/conf.py
test/test_callbacks.py

This allows overriding supybot.reply.mores.instant for private messages, where it is usually more tolerable to send multiple lines.
However, this still defaults to 1, in order to not be abusable by default.

Add config value supybot.reply.mores.instant.whenPrivate

---

plugins/Unix/plugin.py

This PR just add a space in a split to avoid splitting string on first `:` occurence inside an IPv6 with the `ping` command.

[Unix] fix: add space to avoid breaking ipv6 formating

---

src/registry.py
test/test_registry.py

registry: Avoid calling Value.setValue() when closing registry

---

src/commands.py
test/test_commands.py

For example, this allows giving negative GPS coordinations to [`NuWeather`'s `@weather` command](https://github.com/jlu5/Limnoria-NuWeather/blob/18b9cbc8d8a04fda405a9e50d0b1dd3c216ecae9/plugin.py#L520-L522):
```py
@wrap([getopts({'user': 'nick', 'backend': None, 'weather-backend': None, 'geocode-backend': None, 'forecast': ''}), additional('text')])
def weather(self, irc, msg, args, optlist, location):
"""[--user <othernick>] [--weather-backend/--backend <weather backend>] [--geocode-backend <geocode backend>] [--forecast] [<location>]
```

Add support for negative integers options following getopt

---

plugins/RSS/plugin.py
plugins/RSS/test.py

Added `--random` flag for 'rss' command. It is randomizing initial order of rss entries. So you get random entry of given rss feed after every new call with this flag.
Fixes #1593.

Added --random flag for 'rss' command

---

plugins/ChannelStats/config.py

This assumption no longer true since #1601.
Resolves #1604.

ChannelStats: Fix crash caused by expectation of __str__ being called before setValue

---

plugins/NickAuth/plugin.py
plugins/NickAuth/test.py

On modern networks, account names are usually separated from your current nick, so the idea of registering "nicks" is confusing. For instance, you can be using a grouped nick that is not your main account name, and WHOIS will only ever show that you are logged in to your main account name.
Also, the bot username is optional in the `add` and `remove` commands - update the docs to reflect that.

NickAuth: refer to "services accounts" instead of "nicks" in help

---

plugins/Aka/plugin.py
plugins/Factoids/plugin.py
plugins/Google/plugin.py
plugins/Relay/plugin.py
plugins/Success/plugin.py
src/callbacks.py
src/commands.py
src/conf.py
src/dynamicScope.py
src/log.py
test/test_dynamicScope.py

Some notes:
- I'm using UserWarning here because Python doesn't show DeprecationWarnings to the console by default. (I'm not sure if changing that would be a better option)

Deprecate using supybot.dynamicScope without an import

---

src/plugin.py

pkg_resources will be removed by setuptools before the end of 2025.
Resolves #1631

Use importlib.metadata instead of pkg_resources when possible

---

src/scripts/limnoria_plugin_create.py

setuptools continues the war against its own users and finally managed to break Limnoria.
More specifically, it now has "build isolation" by default, which means that even if users have Limnoria installed,
`from supybot.setup import plugin_setup` fails unless there is a pyproject.toml that contains:
```
[build-system]
requires = ['limnoria', 'setuptools']
```
and then even if we do that, Limnoria's `src/setup.py` crashes while importing the plugin (to read its metadata and class name).
So instead, let's switch to pyproject.toml and hope this doesn't break again in a couple of years.

Replace setup.py with pyproject.toml in the plugin template

---

.github/workflows/test.yml
src/test.py
src/utils/python.py

cffi 2.0 was published this week and broke support for some 3.14 alpha versions. This caused a segfault when trying to use python3-cryptography for ecdsa

CI: Update 3.14 from alpha1 to rc2
